### ISSUE TITLE
Request 

### ISSUE THREAD

**Issue by adizam** [sparkfun/Pokedex#1]
Would love one for an iPhone6s and an iPhone6s Plus. Are you near able to sell? I could investigate doing it myself but I'm new to the 3D printing world!

**Comment by DeadliestAsian** [comment]
I would pay a handsome amount for one for my s7 edge also. Unfortunately 3D printers are out of my reach or understanding atm but...everyone loves pokemon. Willing to pay extra for a belt clip for it too!

**Comment by bboyho** [comment]
Hi,

I happened to come across this issue when checking out this repository. Sorry for the delay in reply. The project files were released to the public for those interested in adjusting the models and making their own case. We are not planning on selling the cases as a product. There are some models with the Kanto Pokédex. You may need to modify the files to get it working with your phone if you are still using your iPhone6.

To modify, you will need a 3D modeling program (like Fusion 360, Tinkercad). If you do not have experience modifying 3D models, you may want to check out this tutorial on [Getting Started with 3D Printing Using Tinkercad](https://learn.sparkfun.com/tutorials/getting-started-with-3d-printing-using-tinkercad/) for an idea on how to design and print an enclosure. You'll need a [3D printer](https://www.sparkfun.com/categories/365) to print the models. If you don't have one, try checking a local maker space.
