### ISSUE TITLE
Error in Files

### ISSUE THREAD

**Issue by DRA6N** [sparkfun/Pokedex#14]
When trying to open any of the .skp files I get an error, they are corrupted. Also the .obj won't import into any of my 3d software for some reason. can you convert those files to .STL please??

**Comment by NPoole** [comment]
Please clone the entire repo to your machine or download the zipped archive. I've just double checked and the files open fine on my end. Downloading the raw files individually doesn't work for some reason that I can't correct on my end. Let me know if you still have trouble :)
