### ISSUE TITLE
sketchup files broken

### ISSUE THREAD

**Issue by darknessblade** [sparkfun/Pokedex#17]
using sketchup 2016 (free)
## i get a message this file does not seems to be a sketchup file.

also i am planning to make a (unova/other) region dex case (depending on how good i can create it in sketchup) (will send photo's if i have made it).
[http://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9dex](url)

it might be a fun idea to inbedd a pokemon go + module slot in the dex,

**Comment by bboyho** [comment]
Hi,

I happened to come across this issue when checking out this repository. Sorry for the delay in reply. Try cloning the entire repository or downloading the zipped archive. Several people have reported that downloading the raw files individually yields corrupted models. Thanks!
