### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Diabetus90** [sparkfun/Pokedex#2]
I am interested to see if a case could be made for the Motorola Droid Ultra and how much it would cost to do so?

**Comment by Diabetus90** [comment]
Also if one could be made for the Iphone 5S?

**Comment by bboyho** [comment]
Hi,

I happened to come across this issue when checking out this repository. Sorry for the delay in reply. The project files were released to the public for those interested in adjusting the models and making their own case. There are no plans on adjusting the files or selling the case as a product for the Motorola Droid Ultra or iPhone 5S. However, it looks like someone in the community tried making a universal body design [ [https://github.com/sparkfun/Pokedex/issues/8](https://github.com/sparkfun/Pokedex/issues/8) ] after [forking this repository](https://github.com/sparkfun/Pokedex/network/members). 

To modify, you will need a 3D modeling program (like Fusion 360, Tinkercad). If you do not have experience modifying 3D models, you may want to check out this tutorial on [Getting Started with 3D Printing Using Tinkercad](https://learn.sparkfun.com/tutorials/getting-started-with-3d-printing-using-tinkercad/) for an idea on how to design and print an enclosure. You'll need a [3D printer](https://www.sparkfun.com/categories/365) to print the models. If you don't have one, try checking a local maker space.
