### ISSUE TITLE
Samsung Galaxy S7 edge

### ISSUE THREAD

**Issue by BuckyDeathwish** [sparkfun/Pokedex#20]
Would lobe to see a design for the s7 edge, i have access to everything i need but not to knowledgeable about design. If you could retune the design for me that would be amazing

**Comment by Thelvaen** [comment]
I'd love to get my hands on the designed tuned for the S7 Edge too.

**Comment by bboyho** [comment]
Hi,

I happened to come across this issue when checking out this repository. Sorry for the delay in reply. The project files were released to the public for those interested in adjusting the models and making their own case. There are no plans on adjusting the files for the Galaxy S7 Edge. However, it looks like someone in the community tried making a universal body design [ [https://github.com/sparkfun/Pokedex/issues/8](https://github.com/sparkfun/Pokedex/issues/8) ] after [forking this repository](https://github.com/sparkfun/Pokedex/network/members). 

To modify, you will need a 3D modeling program (like Fusion 360, Tinkercad). If you do not have experience modifying 3D models, you may want to check out this tutorial on [Getting Started with 3D Printing Using Tinkercad](https://learn.sparkfun.com/tutorials/getting-started-with-3d-printing-using-tinkercad/) for an idea on how to design and print an enclosure.
