### ISSUE TITLE
Pokedex s7 iPhone 6s

### ISSUE THREAD

**Issue by OriginalTitan** [sparkfun/Pokedex#22]
This is a sick case! Need about 4 for the s7, 1 s7 edge and 1 iPhone 6s. Possibly a few more, hope you get to where you can start taking orders soon! Good luck with this project!!

**Comment by bboyho** [comment]
Hi,

I happened to come across this issue when checking out this repository. Sorry for the delay in reply. The project files were released to the public for those interested in adjusting the models and making their own case. There are no plans on adjusting the files for the S7. There should be some files associated with the iPhone 6S. You may need to tweak the model slightly for your phone after printing.

To modify, you will need a 3D modeling program (like Fusion 360, Tinkercad). If you do not have experience modifying 3D models, you may want to check out this tutorial on [Getting Started with 3D Printing Using Tinkercad](https://learn.sparkfun.com/tutorials/getting-started-with-3d-printing-using-tinkercad/) for an idea on how to design and print an enclosure. You'll need a [3D printer](https://www.sparkfun.com/categories/365) to print the models. If you don't have one, try checking a local maker space.
