### ISSUE TITLE
Request LG G4

### ISSUE THREAD

**Issue by mrgmatthews** [sparkfun/Pokedex#25]
Would like this case please. 
Ive made modifications myself but not confident with the 9% overall size increase and some stretching.
Would be nice for this or some suggestions in the sketchup process to do this myself.
Classic design ideally please

**Comment by bboyho** [comment]
Hi,

I happened to come across this issue when checking out this repository. Sorry for the delay in reply. The project files were released to the public for those interested in adjusting the models and making their own case. There are no plans on adjusting the files for the LG G4. However, it looks like someone in the community tried making a universal body design [ [https://github.com/sparkfun/Pokedex/issues/8](https://github.com/sparkfun/Pokedex/issues/8) ] after [forking this repository](https://github.com/sparkfun/Pokedex/network/members). 

If you do not have experience modifying 3D models, you may want to check out this tutorial on [Getting Started with 3D Printing Using Tinkercad](https://learn.sparkfun.com/tutorials/getting-started-with-3d-printing-using-tinkercad/) for an idea on how to design and print an enclosure in general.
