### ISSUE TITLE
S6 Edge+ Possible Adjustment?

### ISSUE THREAD

**Issue by cmac17** [sparkfun/Pokedex#26]
I heard that the new model will work for phones up to 5.5," but the s6 edge plus has a 5.7" screen. I was hoping to buy one once the pricing was released, but I wouldn't want to do that ifor it wouldn't be able to fit my phone. Just thought I'd mention that 5.5" isn't the largest phone out there.

On the other hand, maybe I'll just buy one for my old iphone.

**Comment by bboyho** [comment]
Hi,

I happened to come across this issue when checking out this repository. Sorry for the delay in reply. The project files were released to the public for those interested in adjusting the models and making their own case. There are no plans on adjusting the files or selling the case as a product for the S6 edge. However, it looks like someone in the community tried making a universal body design [ [https://github.com/sparkfun/Pokedex/issues/8](https://github.com/sparkfun/Pokedex/issues/8) ] after forking this repository.

To modify, you will need a 3D modeling program (like Fusion 360, Tinkercad). If you do not have experience modifying 3D models, you may want to check out this tutorial on [Getting Started with 3D Printing Using Tinkercad](https://learn.sparkfun.com/tutorials/getting-started-with-3d-printing-using-tinkercad/) for an idea on how to design and print an enclosure. You'll need a [3D printer](https://www.sparkfun.com/categories/365) to print the models. If you don't have one, try checking a local maker space.
