### ISSUE TITLE
Who can sell me this product?

### ISSUE THREAD

**Issue by ijustpooped69** [sparkfun/Pokedex#27]
I would like a pokedex case with the led lights, battery attachment, and the built in fan for my iphone 5s.

**Comment by markingle** [comment]
Im almost done with a Galaxy S4 design.  Should be ready tomorrow.

**Comment by bboyho** [comment]
Hi,

I happened to come across this issue when checking out this repository. Sorry for the delay in reply. The project files were released to the public for those interested in adjusting the models and making their own case. There are no plans on adjusting the files or selling the cases as a product for the iPhone 5s and Galaxy S4.

To modify, you will need a 3D modeling program (like Fusion 360, Tinkercad). If you do not have experience modifying 3D models, you may want to check out this tutorial on [Getting Started with 3D Printing Using Tinkercad](https://learn.sparkfun.com/tutorials/getting-started-with-3d-printing-using-tinkercad/) for an idea on how to design and print an enclosure. You'll need a [3D printer](https://www.sparkfun.com/categories/365) to print the models. If you don't have one, try checking a local maker space.
