### ISSUE TITLE
Compact Kanto is worng size for the iPhone 6s thickness

### ISSUE THREAD

**Issue by Masterwolf2050** [sparkfun/Pokedex#29]
I found that the opening for the iphone 6s Compact Kanto was to big for the phones thickness. have to use a folded sheet of paper and a piece of cardboard

**Comment by NPoole** [comment]
Oh no! As soon as I get my iPhone dummies in the mail, I'll correct the model!

**Comment by bboyho** [comment]
Hi,

I happened to come across this issue when checking out this repository. Sorry for the delay in reply. The project files were released to the public for those interested in adjusting the models and making their own case. There are no plans on adjusting the files located in the compact Kanto folder. 

To modify, you will need a 3D modeling program (like Fusion 360, Tinkercad). If you do not have experience modifying 3D models, you may want to check out this tutorial on [Getting Started with 3D Printing Using Tinkercad](https://learn.sparkfun.com/tutorials/getting-started-with-3d-printing-using-tinkercad/) for an idea on how to design and print an enclosure. You'll need a [3D printer](https://www.sparkfun.com/categories/365) to print the models. If you don't have one, try checking a local maker space.
