### ISSUE TITLE
HTC 10

### ISSUE THREAD

**Issue by jimjam612** [sparkfun/Pokedex#31]
hi, AWESOME thing you got going here. I just have a small concern. I love Pokemon and always have. I would be thrilled to get my hand on this little gadget but from what I have read i do not think my phone will fit. If i remember the parameters of the universal Kanto Pokedex correct then I think my phone is just barely too big... is there anyway you could look into this? I have access to a few printing services in the area I live but my design skills are... well poor. I have the HTC 10. it was released earlier this year. any advice or solution would be greatly appreciated. Thank you for all of the time and effort you have put into this project!! Keep up the great work because this is amazing!!! I look forward to your future ideas/projects.

**Comment by bboyho** [comment]
Hi,

I happened to come across this issue when checking out this repository. Sorry for the delay in reply. The project files were released to the public for those interested in adjusting the models and making their own case. There are no plans on adjusting the files for the HTC 10. However, it looks like someone in the community tried making a universal body design [ [https://github.com/sparkfun/Pokedex/issues/8](https://github.com/sparkfun/Pokedex/issues/8) ] after [forking this repository](https://github.com/sparkfun/Pokedex/network/members). 

To modify, you will need a 3D modeling program (like Fusion 360, Tinkercad). If you do not have experience modifying 3D models, you may want to check out this tutorial on [Getting Started with 3D Printing Using Tinkercad](https://learn.sparkfun.com/tutorials/getting-started-with-3d-printing-using-tinkercad/) for an idea on how to design and print an enclosure.
