### ISSUE TITLE
Files to OBJ format

### ISSUE THREAD

**Issue by Foxxel** [sparkfun/Pokedex#6]
Could we get version of the files as OBJ?

**Comment by Foxxel** [comment]
Mainly asking this as the one obj file that is in here won't open with really any programs. Keeps throwing errors

**Comment by bboyho** [comment]
Hi,

I happened to come across this issue when checking out this repository. Sorry for the delay in reply. The project files were released to the public for those interested in adjusting the models and making their own case. 

Try cloning the entire repository or downloading the zipped archive. Several people have reported that downloading the raw files individually yields corrupted models. Thanks!
