### ISSUE TITLE
Universal body design for most phones

### ISSUE THREAD

**Issue by jamesalmeida** [sparkfun/Pokedex#8]
Since people are asking for multiple phones to work with this design maybe it would be better to make a body that could accept an extra piece that is custom for different phones. Then anyone can just make an insert for an iPhone 5s or Galaxy s7 and use it in the same body but with their respective insert. Would this work?

**Comment by Foxxel** [comment]
Yes to this; I mean my only want is to be able to charge this while in the case. Really don't need to worry about space for extra battery since I already own a power bank.

**Comment by jamesalmeida** [comment]
Looks like this is getting done here: https://github.com/sparkfun/Pokedex/issues/18

**Comment by bboyho** [comment]
Hi,

I happened to come across this issue when checking out this repository. Sorry for the delay in reply. The project files were released to the public for those interested in adjusting the models and making their own case. There are no plans at SparkFun to adjust the files for the a universal body design.

To modify, you will need a 3D modeling program (like Fusion 360, Tinkercad). If you do not have experience modifying 3D models, you may want to check out this tutorial on [Getting Started with 3D Printing Using Tinkercad](https://learn.sparkfun.com/tutorials/getting-started-with-3d-printing-using-tinkercad/) for an idea on how to design and print an enclosure. You'll need a [3D printer](https://www.sparkfun.com/categories/365) to print the models. If you don't have one, try checking a local maker space.
