### ISSUE TITLE
Willing to pay Top Dollar for S7 edge model and if possible belt clip.

### ISSUE THREAD

**Issue by DeadliestAsian** [sparkfun/Pokedex#9]
I would pay a handsome amount for one for my s7 edge also. Unfortunately 3D printers are out of my reach or understanding atm but...everyone loves pokemon. Willing to pay extra for a belt clip for it too!

**Comment by bboyho** [comment]
Hi,

I happened to come across this issue when checking out this repository. Sorry for the delay in reply. The project files were released to the public for those interested in adjusting the models and making their own case. There are no plans on adjusting the files or selling the case as a product for the S7. However, it looks like someone in the community tried making a universal body design [ [https://github.com/sparkfun/Pokedex/issues/8](https://github.com/sparkfun/Pokedex/issues/8) ] after [forking this repository](https://github.com/sparkfun/Pokedex/network/members). 

To modify, you will need a 3D modeling program (like Fusion 360, Tinkercad). If you do not have experience modifying 3D models, you may want to check out this tutorial on [Getting Started with 3D Printing Using Tinkercad](https://learn.sparkfun.com/tutorials/getting-started-with-3d-printing-using-tinkercad/) for an idea on how to design and print an enclosure. You'll need a [3D printer](https://www.sparkfun.com/categories/365) to print the models. If you don't have one, try checking a local maker space.
